---
version: 5
defaults:
  datadir: /vagrant/environments/vagrant/manifests/
  data_hash: yaml_data

hierarchy:
  - name: Hostname
    path: "%{::hostname}.yaml"
  - name: Hostname minus index is role (custom fact)
    path: "role_%{::role}.yaml"
